#BA572 Final Project Notebook

In [198]:
%%capture
# install the package used for statistical analyses
!pip install pingouin
!pip install Stargazer
!pip install pyfixest



#Importing the necessary libraries.
import numpy as np
import pandas as pd
import pingouin as pg
import statsmodels.api as sm
import statsmodels.formula.api as smf
from stargazer.stargazer import Stargazer
import pyfixest as pf



#Reading the data from colab.
from google.colab import drive
drive.mount('/content/drive')

##Preparing the Data For Experiment Analysis

In [199]:
#Read the excel file into the code.
results_df = pd.read_excel('/content/drive/MyDrive/BA572 Project/BA572_Project_April 17, 2026_11.33.xlsx')

#Check how the dataset looks.
results_df.head()

/usr/local/lib/python3.12/dist-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,StartDate,EndDate,Status,IPAddress,Progress,Duration (in seconds),Finished,RecordedDate,ResponseId,RecipientLastName,RecipientFirstName,RecipientEmail,ExternalReference,LocationLatitude,LocationLongitude,DistributionChannel,UserLanguage,Q16_First Click,Q16_Last Click,Q16_Page Submit,Q16_Click Count,QID19,Q20_First Click,Q20_Last Click,Q20_Page Submit,Q20_Click Count,Q22,Q23_First Click,Q23_Last Click,Q23_Page Submit,Q23_Click Count,Q25,Q26_First Click,Q26_Last Click,Q26_Page Submit,Q26_Click Count,Q28,Q65_First Click,Q65_Last Click,Q65_Page Submit,Q65_Click Count,Q67,Q68_First Click,Q68_Last Click,Q68_Page Submit,Q68_Click Count,Q70,Q71_First Click,Q71_Last Click,Q71_Page Submit,Q71_Click Count,Q73,Q74_First Click,Q74_Last Click,Q74_Page Submit,Q74_Click Count,Q76,Q41_First Click,Q41_Last Click,Q41_Page Submit,Q41_Click Count,Q43,Q44_First Click,Q44_Last Click,Q44_Page Submit,Q44_Click Count,Q46,Q47_First Click,Q47_Last Click,Q47_Page Submit,Q47_Click Count,Q49,Q50_First Click,Q50_Last Click,Q50_Page Submit,Q50_Click Count,Q52,Q53_First Click,Q53_Last Click,Q53_Page Submit,Q53_Click Count,Q55,Q56_First Click,Q56_Last Click,Q56_Page Submit,Q56_Click Count,Q58,Q59_First Click,Q59_Last Click,Q59_Page Submit,Q59_Click Count,Q61,Q62_First Click,Q62_Last Click,Q62_Page Submit,Q62_Click Count,Q64,Q78_First Click,Q78_Last Click,Q78_Page Submit,Q78_Click Count,Q80,Q81_First Click,Q81_Last Click,Q81_Page Submit,Q81_Click Count,Q83,Q84_First Click,Q84_Last Click,Q84_Page Submit,Q84_Click Count,Q86,Q87_First Click,Q87_Last Click,Q87_Page Submit,Q87_Click Count,Q89,Q90_First Click,Q90_Last Click,Q90_Page Submit,Q90_Click Count,Q92,Q93_First Click,Q93_Last Click,Q93_Page Submit,Q93_Click Count,Q95,Q96_First Click,Q96_Last Click,Q96_Page Submit,Q96_Click Count,Q98,Q99_First Click,Q99_Last Click,Q99_Page Submit,Q99_Click Count,Q101,Q11,Q12,Q13,Q14,Q15,Q1,Q2,Q4,Q5,Q6,Q7,Q8,Q9,Q103,Q103_4_TEXT,Q10,Group = Control Group,Group = Real Live Action Treatment Group,Group = AI Live Action Treatment Group
0,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to wat...,Do your friends like Anime?,Do you find that animation is for kids only?,"Do you like animated shows (Invincible, Teen T...","Do you like Anime (Jujutsu Kaisen, Naruto, Att...","Do you like Live-action shows (The Boys, MCU, ...",What is your favorite genre(s) of Film/TV?,How many TV shows do you watch monthly on aver...,How much YouTube do you watch on average?,How much TikTok/Instagram do you watch on aver...,Do you interact with others on social media fr...,Which social media platform(s) do you use? (Se...,Where do you currently live?,What is your ethnicity?,What is your gender? - Selected Choice,What is your gender? - Other - Text,What is your age(each range is inclusive)?,Group = Control Group,Group = Real Live Action Treatment Group,Group = AI Live Action Treatment Group
1,2026-04-09 19:20:52,2026-04-09 19:26:52,1,NaN,100,360,1,2026-04-09 19:26:53.070000,R_5l3lEKNxUHSsoU1,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15.006,0,10,0,0,15.008,0,5,0,0,15.105,0,9,0,0,15.006,0,8,0,0,15.007,0,10,0,0,9.584,0,7,0,0,6.951,0,9,0,0,6.011,0,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,5,5,3,1,2,5,1,1,"1,2,3",3,6,NaN,NaN,1,NaN,NaN,NaN
2,2026-04-10 08:57:44,2026-04-10 08:59:40,1,NaN,100,115,1,2026-04-10 08:59:40.845000,R_5PXzLa2r2zcevYX,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,9.585,0,9,2.94,2.94,4.578,1,8,0,0,4.099,0,10,0,0,2.156,0,9,0,0,13.166,0,7,4.049,5.016,5.388,2,8,0,0,4.841,0,8,0,0,5.821,0,9,4,1,4,4,3,"4,5,6",3,2,5,1,"1,6",3,3,NaN,NaN,1,NaN,NaN,NaN
3,2026-04-10 18:12:39,2026-04-10 18:16:28,1,NaN,100,229,1,2026-04-10 18:16:28.658000,R_7h0gOTqOJZyGkJm,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,0,0,15.008,0,9,0,0,15.007,0,10,0,0,15.007,0,8,0,0,15.108,0,6,0,0,15.008,0,9,0,0,15.007,0,9,0,0,15.007,0,8,0,0,15.008,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,4,4,4,"3,4,5",3,2,5,1,"4,5,6",2,5,NaN,NaN,3,NaN,NaN,NaN
4,2026-04-10 18:18:45,2026-04-10 18:19:57,1,NaN,100,71,1,2026-04-10 18:19:57.487000,R_5Nwjr1aPrIMiL21,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.373,0,7,0,0,1.77,0,10,0,0,1.57,0,5,0,0,1.492,0,9,0,0,2.087,0,5,0,0,3.517,0,7,0,0,2.143,0,9,7.727,7.727,7.996,1,9,5,4,3,3,4,"3,5",3,1,3,2,3,6,3,NaN,NaN,3,NaN,NaN,NaN

In [200]:
#Fix weird formatting given by Qualtrics when downloading the Excel file.
results_df.columns = results_df.iloc[0]
results_df = results_df[1:].reset_index(drop=True)
results_df.head()

,Start Date,End Date,Response Type,IP Address,Progress,Duration (in seconds),Finished,Recorded Date,Response ID,Recipient Last Name,Recipient First Name,Recipient Email,External Data Reference,Location Latitude,Location Longitude,Distribution Channel,User Language,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Timing - First Click,Timing - Last Click,Timing - Page Submit,Timing - Click Count,Please rate how likely you are to click to watch based on the poster,Do your friends like Anime?,Do you find that animation is for kids only?,"Do you like animated shows (Invincible, Teen Titans, or Avatar: The Last Airbender)?","Do you like Anime (Jujutsu Kaisen, Naruto, Attack on Titan, etc.)?","Do you like Live-action shows (The Boys, MCU, etc):",What is your favorite genre(s) of Film/TV?,How many TV shows do you watch monthly on average?,How much YouTube do you watch on average?,How much TikTok/Instagram do you watch on average?,Do you interact with others on social media frequently(10-20 messages per day)?,Which social media platform(s) do you use? (Select all that apply):,Where do you currently live?,What is your ethnicity?,What is your gender? - Selected Choice,What is your gender? - Other - Text,What is your age(each range is inclusive)?,Group = Control Group,Group = Real Live Action Treatment Group,Group = AI Live Action Treatment Group
0,2026-04-09 19:20:52,2026-04-09 19:26:52,1,NaN,100,360,1,2026-04-09 19:26:53.070000,R_5l3lEKNxUHSsoU1,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15.006,0,10,0,0,15.008,0,5,0,0,15.105,0,9,0,0,15.006,0,8,0,0,15.007,0,10,0,0,9.584,0,7,0,0,6.951,0,9,0,0,6.011,0,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,5,5,3,1,2,5,1,1,"1,2,3",3,6,NaN,NaN,1,NaN,NaN,NaN
1,2026-04-10 08:57:44,2026-04-10 08:59:40,1,NaN,100,115,1,2026-04-10 08:59:40.845000,R_5PXzLa2r2zcevYX,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,9.585,0,9,2.94,2.94,4.578,1,8,0,0,4.099,0,10,0,0,2.156,0,9,0,0,13.166,0,7,4.049,5.016,5.388,2,8,0,0,4.841,0,8,0,0,5.821,0,9,4,1,4,4,3,"4,5,6",3,2,5,1,"1,6",3,3,NaN,NaN,1,NaN,NaN,NaN
2,2026-04-10 18:12:39,2026-04-10 18:16:28,1,NaN,100,229,1,2026-04-10 18:16:28.658000,R_7h0gOTqOJZyGkJm,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,0,0,15.008,0,9,0,0,15.007,0,10,0,0,15.007,0,8,0,0,15.108,0,6,0,0,15.008,0,9,0,0,15.007,0,9,0,0,15.007,0,8,0,0,15.008,0,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,4,4,4,"3,4,5",3,2,5,1,"4,5,6",2,5,NaN,NaN,3,NaN,NaN,NaN
3,2026-04-10 18:18:45,2026-04-10 18:19:57,1,NaN,100,71,1,2026-04-10 18:19:57.487000,R_5Nwjr1aPrIMiL21,NaN,NaN,NaN,NaN,42.3464,-71.0975,preview,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,1.373,0,7,0,0,1.77,0,10,0,0,1.57,0,5,0,0,1.492,0,9,0,0,2.087,0,5,0,0,3.517,0,7,0,0,2.143,0,9,7.727,7.727,7.996,1,9,5,4,3,3,4,"3,5",3,1,3,2,3,6,3,NaN,NaN,3,NaN,NaN,NaN
4,2026-04-11 12:05:22,2026-04-11 12:08:40,0,128.197.28.160,100,197,1,2026-04-11 12:08:40.501000,R_6GBa0ynNrnpLUzI,NaN,NaN,NaN,NaN,42.3464,-71.0975,anonymous,EN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,0,15.01,0,3,0,0,10.196,0,1,0,0,4.677,0,8,0,0,5.648,0,4,0,0,4.03,0,5,0,0,4.723,0,8,0,0,2.928,0,3,0,0,3.802,0,5,5,1,5,5,4,"2,4,6",2,1,1,1,"1,3,4,5",3,1,NaN,NaN,3,NaN,NaN,NaN

In [201]:
#Check the columns in the Dataset.
results_df.columns

Index(['Start Date', 'End Date', 'Response Type', 'IP Address', 'Progress',
       'Duration (in seconds)', 'Finished', 'Recorded Date', 'Response ID',
       'Recipient Last Name',
       ...
       'Do you interact with others on social media frequently(10-20 messages per day)?',
       'Which social media platform(s) do you use? (Select all that apply):',
       'Where do you currently live?', 'What is your ethnicity?',
       'What is your gender? - Selected Choice',
       'What is your gender? - Other - Text',
       'What is your age(each range is inclusive)?', 'Group = Control Group',
       'Group = Real Live Action Treatment Group',
       'Group = AI Live Action Treatment Group'],
      dtype='object', name=0, length=156)

In [202]:
#Remove redundant or useless columns from the dataset.

#Initialize a list of those columns to remove.
cols_to_drop = [
    'Start Date', 'End Date', 'Response Type', 'IP Address', 'Progress',
    'Finished', 'Recorded Date', 'Response ID',
    'Recipient Last Name', 'Recipient First Name', 'Recipient Email',
    'External Data Reference', 'Location Latitude', 'Location Longitude',
    'Distribution Channel', 'User Language', 'Timing - First Click','Timing - Last Click',
    'Timing - Page Submit','Timing - Click Count'
]


#Drop the unnecessary columns
results_df_trimmed = results_df.drop(columns=cols_to_drop, errors='ignore')
results_df_trimmed.head()

,Duration (in seconds),Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Please rate how likely you are to click to watch based on the poster,Do your friends like Anime?,Do you find that animation is for kids only?,"Do you like animated shows (Invincible, Teen Titans, or Avatar: The Last Airbender)?","Do you like Anime (Jujutsu Kaisen, Naruto, Attack on Titan, etc.)?","Do you like Live-action shows (The Boys, MCU, etc):",What is your favorite genre(s) of Film/TV?,How many TV shows do you watch monthly on average?,How much YouTube do you watch on average?,How much TikTok/Instagram do you watch on average?,Do you interact with others on social media frequently(10-20 messages per day)?,Which social media platform(s) do you use? (Select all that apply):,Where do you currently live?,What is your ethnicity?,What is your gender? - Selected Choice,What is your gender? - Other - Text,What is your age(each range is inclusive)?,Group = Control Group,Group = Real Live Action Treatment Group,Group = AI Live Action Treatment Group
0,360,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10,5,9,8,10,7,9,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,1,5,5,3,1,2,5,1,1,"1,2,3",3,6,NaN,NaN,1,NaN,NaN,NaN
1,115,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9,8,10,9,7,8,8,9,4,1,4,4,3,"4,5,6",3,2,5,1,"1,6",3,3,NaN,NaN,1,NaN,NaN,NaN
2,229,9,10,8,6,9,9,8,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,4,4,4,4,"3,4,5",3,2,5,1,"4,5,6",2,5,NaN,NaN,3,NaN,NaN,NaN
3,71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7,10,5,9,5,7,9,9,5,4,3,3,4,"3,5",3,1,3,2,3,6,3,NaN,NaN,3,NaN,NaN,NaN
4,197,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,1,8,4,5,8,3,5,5,1,5,5,4,"2,4,6",2,1,1,1,"1,3,4,5",3,1,NaN,NaN,3,NaN,NaN,NaN

In [203]:
#Check for the leftover columns in the dataset.
results_df_trimmed.columns

Index(['Duration (in seconds)',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Please rate how likely you are to click to watch based on the poster',
       'Do your friends like Anime?',
       'Do you find that animation is for kids only?',
       'Do you like animated shows (Invincible, Teen Titans, or Avatar: The Last Airbender)?',
       'Do you like Anime (Jujutsu Kaisen, Naruto, Attack on Titan, etc.)?',
       'Do you like Live-action shows (The Boys, MCU, etc):',
       'What is your favorite genre(s) of Film/TV?',
       'How many TV shows do you watch monthly on average?',
       'How much YouTube do you watch on average?',
       'How much TikTok/Instagram do you watch on average?',
       'Do you interact with others on social media frequently(10-20 messages per day)?',
       'Which social media platform(s) do you use? (Select all that apply):',
       'Where do you currently live?', 'What is your ethnicity?',
       'What is your gender? - Selected Choice',
       'What is your gender? - Other - Text',
       'What is your age(each range is inclusive)?', 'Group = Control Group',
       'Group = Real Live Action Treatment Group',
       'Group = AI Live Action Treatment Group'],
      dtype='object', name=0)

In [204]:
#Initialize a new variable which only stores the outcome question
#as a list.
poster_cols = [col for col in results_df_trimmed.columns
               if 'Please rate how likely you are to click to watch based on the poster'
               in str(col)]

#Extract the rows of those column from our orignal
#dataframe.
poster_ratings = results_df_trimmed[poster_cols]

#Define a function to determine the group
#based on non-null responses in the 8-column chunks.
#This will be used on the poster ratings column
#so the indicies are accurate.
def assign_group(row):
    if row.iloc[0:8].notna().any():
        return 'Control Group'
    elif row.iloc[8:16].notna().any():
        return 'Treatment Arm 1'
    elif row.iloc[16:24].notna().any():
        return 'Treatment Arm 2'
    else:
        return 'Unknown'

#Apply the function to create the new 'Group' column.
results_df_trimmed['Group'] = poster_ratings.apply(
                                assign_group, axis=1)

#Display the group counts to verify.
#We have at least 30 for each group so we fulfilled
#that requirement.
display(results_df_trimmed['Group'].value_counts())

Group
Treatment Arm 2    41
Treatment Arm 1    40
Control Group      36
Name: count, dtype: int64

In [205]:
#Initialize a dictionary for the starting
#index for each group in our expeirment.
group_start = {
    'Control Group':   0,
    'Treatment Arm 1': 8,
    'Treatment Arm 2': 16,
}


#Create a new varaible, which would show
#the Groups based on their starting index
#(i.e if it is contorl the starts row would have
#0, if it is treatment arm 1, it would have
#8, etc.).
starts = results_df_trimmed['Group'] \
                      .map(group_start)

#For each person, it checks which group they
#are in, determines the starting column to use
#based on the group(i.e. if it is control it
#would start at 0), then adds 4 extra columns
#to that to get the anime rating.
results_df_trimmed['avg_rating_anime'] = [
    poster_ratings.iloc[i, s:s+4].mean() #Based on the person, and which group he is in, start at column index s, and stop 4 columns to the right, and get the mean.
    for i, s in enumerate(starts) #i is the row/person, s is the group that person is in.
]




#For each person, it checks which group they
#are in, determines the starting column to use
#based on the group(i.e. if it is control it
#would start at 0), then adds 4 extra columns
#to that to get the cartoon rating.
results_df_trimmed['avg_rating_cartoon'] = [
    poster_ratings.iloc[i, s+4:s+8].mean()  #Based on the person, and which group he is in, start at column index s, and stop 4 columns to the right, and get the mean.
    for i, s in enumerate(starts) #i is the row/person, s is the group that person is in.
]

In [206]:
#Drop the columnns no longer needed because
#we have group and outcome varaibles now.
clean_df = results_df_trimmed.drop(
    columns=[
        'Please rate how likely you are to click to watch based on the poster',
        'Group = Control Group',
        'Group = Real Live Action Treatment Group',
        'Group = AI Live Action Treatment Group',
        'What is your gender? - Other - Text',
    ],
    errors='ignore'
)

In [208]:
#Rename the columns from being questions in our survey
#to simpler names for readability.

#Define the dicitonary for them.
rename_map = {
    'Duration (in seconds)':                                                                'Duration',
    'Do your friends like Anime?':                                                          'Friends_like_anime',
    'Do you find that animation is for kids only?':                                         'Animation_for_kids',
    'Do you like animated shows (Invincible, Teen Titans, or Avatar: The Last Airbender)?': 'Like_animated_shows',
    'Do you like Anime (Jujutsu Kaisen, Naruto, Attack on Titan, etc.)?':                   'Like_anime',
    'Do you like Live-action shows (The Boys, MCU, etc):':                                  'Like_live_action',
    'What is your favorite genre(s) of Film/TV?':                                           'Genre',
    'How many TV shows do you watch monthly on average?':                                   'Tv_shows_monthly',
    'How much YouTube do you watch on average?':                                            'Youtube_usage',
    'How much TikTok/Instagram do you watch on average?':                                   'Tiktok_instagram_usage',
    'Do you interact with others on social media frequently(10-20 messages per day)?':      'Social_media_active',
    'Which social media platform(s) do you use? (Select all that apply):':                  'Platform',
    'Where do you currently live?':                                                         'Location',
    'What is your ethnicity?':                                                              'Ethnicity',
    'What is your gender? - Selected Choice':                                               'Gender',
    'What is your age(each range is inclusive)?':                                           'Age_group',
    'Group':                                                                                'Group',
}


#Rename the columns in the dataset.
clean_df = clean_df.rename(columns=rename_map)

#Fill the null values in Gender with Prefer not to disclose.
clean_df['Gender'] = clean_df['Gender'].fillna('Prefer not to disclose')

In [209]:
#Survey data from Qualtrics came in as string(text) and
#not numeric datatype so we have to convert them to numeric.

#List of columns that should function like numbers.
numeric_cols = [
    'Duration', 'Friends_like_anime',
    'Animation_for_kids','Like_animated_shows',
    'Like_anime', 'Like_live_action',
    'Tv_shows_monthly', 'Youtube_usage',
    'Tiktok_instagram_usage','Social_media_active',
    'Location', 'Ethnicity', 'Age_group',
]


#Loop through and apply it to each column
#which should be numeric.
for col in numeric_cols:
    clean_df[col] = pd.to_numeric(clean_df[col],
                                  errors='coerce')

In [212]:
#Applying one-hot encoding to change the our genre and
#platform columns, to separte the multiple choices and
#change them into numbers so that our functions can run
#effectively.

#Define a helper function to help with the
#encoding.
def ohe_multiselect(df, col, prefix):

    #Create dummies for the col column,
    #fill its null values with empty string
    #to rpevent crashes, use astype to make
    #sure they are treated as a string,
    #then get dummies with .get_dummeies.
    dummies = (
        df[col]
        .fillna('')
        .astype(str)
        .str.get_dummies(sep=',') #Note we use str.get_dummies because the rows in our columns have stuff like (Tiktok, Snap and not just Tiktok)
    )

    #Remove the empty column we got from fillna().
    dummies = dummies.drop(columns=[''],
                           errors='ignore')  # artifact from NaN rows

    #Rename the columns so that it is clear
    #from which orginal column the dummies
    #came from.
    dummies.columns = [f'{prefix}_{c.strip()}'
                       for c in dummies.columns]

    #Return the dummies.
    return dummies

#Use the helper function to get our dummies.
platform_dummies = ohe_multiselect(clean_df,
                                   'Platform',
                                   'Platform')

genre_dummies = ohe_multiselect(clean_df,
                                   'Genre',
                                   'Genre')

#Add the dummies to our dataframe and remove
#the orignal Platform and Genre columns.
clean_df = pd.concat(
    [clean_df.drop(columns=['Platform', 'Genre']),
     platform_dummies, genre_dummies],
    axis=1,
)

In [213]:
#Rename the newly created dummies into
#more descriptive names(note in qualtrics
#they were automatically converted to numbers
#which is why we are doing this).

#Define the dictionary to use for renaming our columns.
ohe_rename_map = {
    'Platform_1': 'Platform_instagram',
    'Platform_2': 'Platform_tiktok',
    'Platform_3': 'Platform_youtube',
    'Platform_4': 'Platform_reddit',
    'Platform_5': 'Platform_discord',
    'Platform_6': 'Platform_facebook',
    'Platform_7': 'Platform_twitter',
    'Platform_8': 'Platform_snapchat',
    'Genre_1':    'Genre_comedy',
    'Genre_2':    'Genre_action',
    'Genre_3':    'Genre_mystery',
    'Genre_4':    'Genre_romance',
    'Genre_5':    'Genre_sitcom',
    'Genre_6':    'Genre_drama',
}

#Rename the columns with the more descriptive titles.
clean_df = clean_df.rename(columns=ohe_rename_map)

In [ ]:
#Dealing with null values in the data.

print(clean_df.isnull().sum())



clean_df = clean_df.dropna()
print("Null values after dropping:\n", clean_df.isnull().sum())

In [224]:
#Before running the experiment, checking the
#Average outcomes between each of our groups.
avg_ratings_by_group = clean_df.groupby('Group') \
    [['avg_rating_anime', 'avg_rating_cartoon']] \
    .mean()

#Display the resutls as a table
display(avg_ratings_by_group)

                 avg_rating_anime  avg_rating_cartoon
Group
Control Group            5.835714            6.157143
Treatment Arm 1          5.844595            5.614865
Treatment Arm 2          4.719512            5.439024

In [222]:
clean_df.shape

(113, 31)

##Checking for Randomization

In [ ]:
import pingouin as pg
import pandas as pd

# Define the groups
control_group_df = clean_df[clean_df['group'] == 'Control Group']
treatment_arm1_df = clean_df[clean_df['group'] == 'Treatment Arm 1']
treatment_arm2_df = clean_df[clean_df['group'] == 'Treatment Arm 2']

# List of numerical and binary covariates to check for randomization
# Exclude outcome variables and the group column itself
numerical_covariates = [
    'duration', 'friends_like_anime', 'animation_for_kids',
    'like_animated_shows', 'like_anime', 'like_live_action',
    'tv_shows_monthly', 'youtube_usage', 'tiktok_instagram_usage',
    'social_media_active', 'location', 'ethnicity', 'age_group',
    'platform_instagram', 'platform_tiktok', 'platform_youtube',
    'platform_reddit', 'platform_discord', 'platform_facebook',
    'platform_twitter', 'platform_snapchat', 'genre_comedy',
    'genre_action', 'genre_mystery', 'genre_romance', 'genre_sitcom',
    'genre_drama'
]

randomization_check_results = []

print("Performing randomization checks using Pingouin t-test:")

for covariate in numerical_covariates:
    print(f"\n--- Covariate: {covariate} ---")

    # Treatment Arm 1 vs Control Group
    # Use correction=True for Welch's t-test, which does not assume equal variances
    ttest_1_vs_control = pg.ttest(
        x=treatment_arm1_df[covariate],
        y=control_group_df[covariate],
        correction=True
    )
    randomization_check_results.append({
        'Covariate': covariate,
        'Comparison': 'Treatment Arm 1 vs Control Group',
        'p-value': ttest_1_vs_control['p_val'].iloc[0],
        'T': ttest_1_vs_control['T'].iloc[0],
        'df': ttest_1_vs_control['dof'].iloc[0]
    })
    print(f"Treatment Arm 1 vs Control Group:\n{ttest_1_vs_control[['T', 'dof', 'p_val', 'cohen_d']]}")

    # Treatment Arm 2 vs Control Group
    ttest_2_vs_control = pg.ttest(
        x=treatment_arm2_df[covariate],
        y=control_group_df[covariate],
        correction=True
    )
    randomization_check_results.append({
        'Covariate': covariate,
        'Comparison': 'Treatment Arm 2 vs Control Group',
        'p-value': ttest_2_vs_control['p_val'].iloc[0],
        'T': ttest_2_vs_control['T'].iloc[0],
        'df': ttest_2_vs_control['dof'].iloc[0]
    })
    print(f"Treatment Arm 2 vs Control Group:\n{ttest_2_vs_control[['T', 'dof', 'p_val', 'cohen_d']]}")

# Convert results to a DataFrame for better display
randomization_df = pd.DataFrame(randomization_check_results)
print("\n--- Summary of Randomization Check Results ---")
display(randomization_df.round(4))

# Identify covariates with significant differences (e.g., p-value < 0.05)
significant_diffs = randomization_df[randomization_df['p-value'] < 0.05]
if not significant_diffs.empty:
    print("\nCovariates with significant differences (p < 0.05), suggesting potential randomization failure:")
    display(significant_diffs.round(4))
else:
    print("\nNo significant differences found (p < 0.05) between groups for the tested covariates, suggesting successful randomization.")

In [225]:
from statsmodels.stats.proportion import proportions_ztest
import pandas as pd
import numpy as np

# Identify numerical covariates (exclude outcome variables)
covariates = [c for c in clean_df.select_dtypes(include=np.number).columns
              if c not in ['avg_rating_anime', 'avg_rating_cartoon']]

# Split data by group
control_df = clean_df[clean_df['Group'] == 'Control Group']
treat1_df = clean_df[clean_df['Group'] == 'Treatment Arm 1']
treat2_df = clean_df[clean_df['Group'] == 'Treatment Arm 2']

results = []

for col in covariates:
    # Check if column is inherently binary (0 and 1 only)
    is_binary = clean_df[col].dropna().isin([0, 1]).all()

    for treat_name, treat_df in [('Treatment Arm 1', treat1_df), ('Treatment Arm 2', treat2_df)]:
        if is_binary:
            # Direct sum for binary fields
            count = np.array([treat_df[col].sum(), control_df[col].sum()])
            nobs = np.array([len(treat_df[col].dropna()), len(control_df[col].dropna())])
        else:
            # For continuous/ordinal, test proportion above the overall median to avoid count > nobs errors
            med = clean_df[col].median()
            count = np.array([(treat_df[col] > med).sum(), (control_df[col] > med).sum()])
            nobs = np.array([len(treat_df[col].dropna()), len(control_df[col].dropna())])

        try:
            stat, pval = proportions_ztest(count, nobs)
        except Exception:
            stat, pval = np.nan, np.nan

        results.append({
            'Covariate': col,
            'Comparison': f'{treat_name} vs Control',
            'Z-Statistic': stat,
            'p-value': pval,
            'Note': 'Binary Test' if is_binary else 'Prop > Median Test'
        })

# Format and display the results neatly
results_df = pd.DataFrame(results)

print("--- Proportions Z-Test Randomization Check ---")
display(results_df.round(4).style.set_properties(**{'text-align': 'left'}).set_table_styles([
    dict(selector='th', props=[('text-align', 'left')])
]))

--- Proportions Z-Test Randomization Check ---

In [227]:
# Filter the results for p-values < 0.05
significant_ztests = results_df[results_df['p-value'] < 0.05]

if significant_ztests.empty:
    print("No z-tests resulted in a p-value less than 0.05.")
else:
    print("Here are the z-tests with a p-value less than 0.05:")
    display(significant_ztests)

Here are the z-tests with a p-value less than 0.05:

,Covariate,Comparison,Z-Statistic,p-value,Note
5,Animation_for_kids,Treatment Arm 2 vs Control,-2.440830,0.014654,Prop > Median Test
6,Like_animated_shows,Treatment Arm 1 vs Control,2.192098,0.028372,Prop > Median Test
21,Location,Treatment Arm 2 vs Control,2.137493,0.032558,Prop > Median Test

In [228]:
# Separate the results into two distinct variables
ztest_treat1 = results_df[results_df['Comparison'] == 'Treatment Arm 1 vs Control']
ztest_treat2 = results_df[results_df['Comparison'] == 'Treatment Arm 2 vs Control']

# Output the results for Treatment Arm 1 vs Control
print("--- Proportions Z-Test: Treatment Arm 1 vs Control ---")
display(ztest_treat1.round(4))

# Output the results for Treatment Arm 2 vs Control
print("\n--- Proportions Z-Test: Treatment Arm 2 vs Control ---")
display(ztest_treat2.round(4))

--- Proportions Z-Test: Treatment Arm 1 vs Control ---

,Covariate,Comparison,Z-Statistic,p-value,Note
0,Duration,Treatment Arm 1 vs Control,1.8805,0.0600,Prop > Median Test
2,Friends_like_anime,Treatment Arm 1 vs Control,-0.4144,0.6786,Prop > Median Test
4,Animation_for_kids,Treatment Arm 1 vs Control,-0.9370,0.3488,Prop > Median Test
6,Like_animated_shows,Treatment Arm 1 vs Control,2.1921,0.0284,Prop > Median Test
8,Like_anime,Treatment Arm 1 vs Control,-0.9132,0.3611,Prop > Median Test
10,Like_live_action,Treatment Arm 1 vs Control,-0.4087,0.6828,Prop > Median Test
12,Tv_shows_monthly,Treatment Arm 1 vs Control,-1.4258,0.1539,Prop > Median Test
14,Youtube_usage,Treatment Arm 1 vs Control,1.0662,0.2863,Prop > Median Test
16,Tiktok_instagram_usage,Treatment Arm 1 vs Control,0.2790,0.7802,Prop > Median Test
18,Social_media_active,Treatment Arm 1 vs Control,-0.4144,0.6786,Prop > Median Test
20,Location,Treatment Arm 1 vs Control,1.3950,0.1630,Prop > Median Test
22,Ethnicity,Treatment Arm 1 vs Control,-1.5839,0.1132,Prop > Median Test
24,Age_group,Treatment Arm 1 vs Control,0.5871,0.5571,Prop > Median Test
26,Platform_instagram,Treatment Arm 1 vs Control,-0.4799,0.6313,Binary Test
28,Platform_tiktok,Treatment Arm 1 vs Control,0.7381,0.4604,Binary Test
30,Platform_youtube,Treatment Arm 1 vs Control,-1.2569,0.2088,Binary Test
32,Platform_reddit,Treatment Arm 1 vs Control,-1.6400,0.1010,Binary Test
34,Platform_discord,Treatment Arm 1 vs Control,0.4930,0.6220,Binary Test
36,Platform_facebook,Treatment Arm 1 vs Control,-0.0711,0.9433,Binary Test
38,Platform_twitter,Treatment Arm 1 vs Control,-1.7386,0.0821,Binary Test
40,Platform_snapchat,Treatment Arm 1 vs Control,1.8121,0.0700,Binary Test
42,Genre_comedy,Treatment Arm 1 vs Control,0.2230,0.8235,Binary Test
44,Genre_action,Treatment Arm 1 vs Control,-0.7573,0.4489,Binary Test
46,Genre_mystery,Treatment Arm 1 vs Control,-0.4431,0.6577,Binary Test
48,Genre_romance,Treatment Arm 1 vs Control,-0.9148,0.3603,Binary Test
50,Genre_sitcom,Treatment Arm 1 vs Control,-0.9639,0.3351,Binary Test
52,Genre_drama,Treatment Arm 1 vs Control,0.6954,0.4868,Binary Test

--- Proportions Z-Test: Treatment Arm 2 vs Control ---

,Covariate,Comparison,Z-Statistic,p-value,Note
1,Duration,Treatment Arm 2 vs Control,0.5559,0.5782,Prop > Median Test
3,Friends_like_anime,Treatment Arm 2 vs Control,-0.7053,0.4806,Prop > Median Test
5,Animation_for_kids,Treatment Arm 2 vs Control,-2.4408,0.0147,Prop > Median Test
7,Like_animated_shows,Treatment Arm 2 vs Control,-0.1693,0.8656,Prop > Median Test
9,Like_anime,Treatment Arm 2 vs Control,-1.0044,0.3152,Prop > Median Test
11,Like_live_action,Treatment Arm 2 vs Control,-0.4126,0.6799,Prop > Median Test
13,Tv_shows_monthly,Treatment Arm 2 vs Control,-0.7529,0.4515,Prop > Median Test
15,Youtube_usage,Treatment Arm 2 vs Control,-0.1693,0.8656,Prop > Median Test
17,Tiktok_instagram_usage,Treatment Arm 2 vs Control,-0.0867,0.9309,Prop > Median Test
19,Social_media_active,Treatment Arm 2 vs Control,0.2088,0.8346,Prop > Median Test
21,Location,Treatment Arm 2 vs Control,2.1375,0.0326,Prop > Median Test
23,Ethnicity,Treatment Arm 2 vs Control,0.5250,0.5996,Prop > Median Test
25,Age_group,Treatment Arm 2 vs Control,-0.2368,0.8128,Prop > Median Test
27,Platform_instagram,Treatment Arm 2 vs Control,0.9495,0.3423,Binary Test
29,Platform_tiktok,Treatment Arm 2 vs Control,-0.5273,0.5980,Binary Test
31,Platform_youtube,Treatment Arm 2 vs Control,-1.2393,0.2152,Binary Test
33,Platform_reddit,Treatment Arm 2 vs Control,-1.7922,0.0731,Binary Test
35,Platform_discord,Treatment Arm 2 vs Control,-0.7792,0.4359,Binary Test
37,Platform_facebook,Treatment Arm 2 vs Control,1.0929,0.2745,Binary Test
39,Platform_twitter,Treatment Arm 2 vs Control,-0.3565,0.7214,Binary Test
41,Platform_snapchat,Treatment Arm 2 vs Control,0.6031,0.5464,Binary Test
43,Genre_comedy,Treatment Arm 2 vs Control,0.4070,0.6840,Binary Test
45,Genre_action,Treatment Arm 2 vs Control,-1.0202,0.3076,Binary Test
47,Genre_mystery,Treatment Arm 2 vs Control,0.4786,0.6322,Binary Test
49,Genre_romance,Treatment Arm 2 vs Control,-0.5888,0.5560,Binary Test
51,Genre_sitcom,Treatment Arm 2 vs Control,0.5212,0.6023,Binary Test
53,Genre_drama,Treatment Arm 2 vs Control,-0.1941,0.8461,Binary Test